# Generated by Django 2.1 on 2018-08-07 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_char_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moveset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=50)),
                ('attack_type', models.CharField(max_length=50)),
                ('attack_description', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.Character')),
            ],
        ),
        migrations.RemoveField(
            model_name='backward_arial',
            name='character',
        ),
        migrations.RemoveField(
            model_name='backward_throw',
            name='character',
        ),
        migrations.RemoveField(
            model_name='dash_attack',
            name='character',
        ),
        migrations.RemoveField(
            model_name='down_arial',
            name='character',
        ),
        migrations.RemoveField(
            model_name='down_smash',
            name='character',
        ),
        migrations.RemoveField(
            model_name='down_special',
            name='character',
        ),
        migrations.RemoveField(
            model_name='down_throw',
            name='character',
        ),
        migrations.RemoveField(
            model_name='down_tilt',
            name='character',
        ),
        migrations.RemoveField(
            model_name='final_smash',
            name='character',
        ),
        migrations.RemoveField(
            model_name='forward_arial',
            name='character',
        ),
        migrations.RemoveField(
            model_name='forward_smash',
            name='character',
        ),
        migrations.RemoveField(
            model_name='forward_throw',
            name='character',
        ),
        migrations.RemoveField(
            model_name='forward_tilt',
            name='character',
        ),
        migrations.RemoveField(
            model_name='neutral_arial',
            name='character',
        ),
        migrations.RemoveField(
            model_name='neutral_attack',
            name='character',
        ),
        migrations.RemoveField(
            model_name='neutral_special',
            name='character',
        ),
        migrations.RemoveField(
            model_name='side_special',
            name='character',
        ),
        migrations.RemoveField(
            model_name='up_arial',
            name='character',
        ),
        migrations.RemoveField(
            model_name='up_smash',
            name='character',
        ),
        migrations.RemoveField(
            model_name='up_special',
            name='character',
        ),
        migrations.RemoveField(
            model_name='up_throw',
            name='character',
        ),
        migrations.RemoveField(
            model_name='up_tilt',
            name='character',
        ),
        migrations.DeleteModel(
            name='Backward_Arial',
        ),
        migrations.DeleteModel(
            name='Backward_Throw',
        ),
        migrations.DeleteModel(
            name='Dash_Attack',
        ),
        migrations.DeleteModel(
            name='Down_Arial',
        ),
        migrations.DeleteModel(
            name='Down_Smash',
        ),
        migrations.DeleteModel(
            name='Down_Special',
        ),
        migrations.DeleteModel(
            name='Down_Throw',
        ),
        migrations.DeleteModel(
            name='Down_Tilt',
        ),
        migrations.DeleteModel(
            name='Final_Smash',
        ),
        migrations.DeleteModel(
            name='Forward_Arial',
        ),
        migrations.DeleteModel(
            name='Forward_Smash',
        ),
        migrations.DeleteModel(
            name='Forward_Throw',
        ),
        migrations.DeleteModel(
            name='Forward_Tilt',
        ),
        migrations.DeleteModel(
            name='Neutral_Arial',
        ),
        migrations.DeleteModel(
            name='Neutral_Attack',
        ),
        migrations.DeleteModel(
            name='Neutral_Special',
        ),
        migrations.DeleteModel(
            name='Side_Special',
        ),
        migrations.DeleteModel(
            name='Up_Arial',
        ),
        migrations.DeleteModel(
            name='Up_Smash',
        ),
        migrations.DeleteModel(
            name='Up_Special',
        ),
        migrations.DeleteModel(
            name='Up_Throw',
        ),
        migrations.DeleteModel(
            name='Up_Tilt',
        ),
    ]
